### ISSUE TITLE
Action modifies permission of /usr/local/bin

### ISSUE THREAD

**Issue by keis** [rui314/setup-mold#10]
Running this action modifies the permissions of `/usr/local/bin` from the default of the github runners

```
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
    - uses: actions/checkout@v4
    - name: Reveal permissions
      run: ls -l /usr/local
    - uses: rui314/setup-mold@v1
    - name: Reveal permissions
      run: ls -l /usr/local
```

Before
```
drwxrwxrwx  2 root root  4096 Dec 17 22:23 bin
```

After
```
drwxr-xr-x  2 root root  4096 Nov 29 08:58 bin
```

This breaks other actions that assume the default setup and tries to place binaries in `/usr/local/bin`
